### ISSUE TITLE
Support for Cocoapods dependencies

### ISSUE THREAD

**Issue by ljanzik** [letsdev/maven-ios-plugin#14]
It would be a great feature for us if Maven could deal with cocoapods dependencies

**Comment by fkoebel-letsdev** [comment]
The wait is over! Our Maven iOS Plugin is now supporting Cocoapods dependencies.

**Comment by cwack-letsdev** [comment]
Hey guys, this feature is now available.
You are able to use cocoapods with our ios maven plugin.

Thx for the feature request.
